name: MTG Card Prediction Workflow

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'  # Uruchamia się codziennie o północy

jobs:
  download_data:
    runs-on: ubuntu-proxmox
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Ustawienie symlinków do katalogu danych
        run: |
          mkdir -p /home/kuba/actions-runner/data
          ln -sfn /home/kuba/actions-runner/data data

      - name: Ustawienie Pythona
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Instalacja zależności
        run: poetry install

      - name: Uruchomienie download_bulk_data.py
        run: python download_bulk_data.py

      - name: Uruchomienie download_types.py
        run: python download_types.py

  download_images:
    runs-on: ubuntu-proxmox
    needs: download_data
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Ustawienie symlinków do katalogów data i cards
        run: |
          mkdir -p /home/kuba/actions-runner/data
          mkdir -p /home/kuba/actions-runner/cards
          ln -sfn /home/kuba/actions-runner/data data
          ln -sfn /home/kuba/actions-runner/cards cards

      - name: Ustawienie Pythona
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Instalacja zależności
        run: poetry install

      - name: Uruchomienie download_card_images.py
        run: python download_card_images.py

  create_metadata:
    runs-on: ubuntu-proxmox
    needs: download_images
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Ustawienie symlinków do katalogów data i cards
        run: |
          mkdir -p /home/kuba/actions-runner/data
          mkdir -p /home/kuba/actions-runner/cards
          ln -sfn /home/kuba/actions-runner/data data
          ln -sfn /home/kuba/actions-runner/cards cards

      - name: Ustawienie Pythona
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Instalacja zależności
        run: poetry install

      - name: Uruchomienie make_metadata_csv.py
        run: python make_metadata_csv.py

  data_analysis:
    runs-on: ubuntu-proxmox
    needs: create_metadata
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Ustawienie symlinków do katalogów data i cards
        run: |
          mkdir -p /home/kuba/actions-runner/data
          mkdir -p /home/kuba/actions-runner/cards
          mkdir -p /home/kuba/actions-runner/datasets
          ln -sfn /home/kuba/actions-runner/data data
          ln -sfn /home/kuba/actions-runner/cards cards
          ln -sfn /home/kuba/actions-runner/datasets datasets

      - name: Ustawienie Pythona
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Instalacja zależności
        run: poetry install

      - name: Uruchomienie data_analysis.py
        run: python data_analysis.py
