name: MTG Card Prediction Workflow

on:
    push:
        branches:
          - main  
    workflow_dispatch:
    schedule:
    - cron: '0 0 * * *'  # Uruchamia się codziennie o północy

jobs:
  download_data:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Ustawienie symlinków do katalogu danych
        run: |
          mkdir -p /home/kuba/mtg_project/data
          ln -sfn /home/kuba/mtg_project/data data

      - name: Ustawienie Pythona
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install Poetry
        uses: snok/install-poetry@v1

      - name: Instalacja zależności
        run: poetry install -vvv

      - name: Uruchomienie download_bulk_data.py
        run: poetry run python download_bulk_data.py

      - name: Uruchomienie download_types.py
        run: poetry run python download_types.py

  download_images:
    runs-on: self-hosted
    needs: download_data
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Ustawienie symlinków do katalogów data, cards i logs
        run: |
          mkdir -p /home/kuba/mtg_project/data
          mkdir -p /home/kuba/mtg_project/cards
          mkdir -p /home/kuba/mtg_project/logs
          ln -sfn /home/kuba/mtg_project/data data
          ln -sfn /home/kuba/mtg_project/cards cards
          ln -sfn /home/kuba/mtg_project/logs logs

      - name: Ustawienie Pythona
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install Poetry
        uses: snok/install-poetry@v1

      - name: Instalacja zależności
        run: poetry install -vvv

      - name: Uruchomienie download_card_images.py
        run: poetry run python download_card_images.py

  create_metadata:
    runs-on: self-hosted
    needs: download_images
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Ustawienie symlinków do katalogów data, cards, datasets i logs
        run: |
          mkdir -p /home/kuba/mtg_project/data
          mkdir -p /home/kuba/mtg_project/cards
          mkdir -p /home/kuba/mtg_project/datasets
          mkdir -p /home/kuba/mtg_project/logs
          ln -sfn /home/kuba/mtg_project/data data
          ln -sfn /home/kuba/mtg_project/cards cards
          ln -sfn /home/kuba/mtg_project/datasets datasets
          ln -sfn /home/kuba/mtg_project/logs logs

      - name: Ustawienie Pythona
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install Poetry
        uses: snok/install-poetry@v1

      - name: Instalacja zależności
        run: poetry install -vvv

      - name: Uruchomienie make_metadata_csv.py
        run: poetry run python make_metadata_csv.py

  data_analysis:
    runs-on: self-hosted
    needs: create_metadata
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Ustawienie symlinków do katalogów datasets i cards
        run: |
          mkdir -p /home/kuba/mtg_project/cards
          mkdir -p /home/kuba/mtg_project/datasets
          ln -sfn /home/kuba/mtg_project/cards cards
          ln -sfn /home/kuba/mtg_project/datasets datasets

      - name: Ustawienie Pythona
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install Poetry
        uses: snok/install-poetry@v1

      - name: Instalacja zależności
        run: poetry install -vvv

      - name: Uruchomienie data_analysis.py
        run: poetry run python data_analysis.py
