name: MTG Card Prediction Workflow

on:
  push:
    branches:
      - main
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'  # Uruchamia się codziennie o północy

env:
  GLOBAL_PATH: "/home/kuba/mtg_project/"

jobs:
  setup_directories:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Load environment variables
        run: |
          grep -v '^#' .env | while IFS= read -r line; do
            echo "$line" >> $GITHUB_ENV
          done

      - name: Debug environment variables
        run: |
          echo "Debugging environment variables:"
          env | grep GLOBAL_PATH
          env | grep DATA_DIR_PATH
          env | grep CARDS_DIR_PATH
          env | grep LOGS_DIR_PATH
          env | grep DATASETS_DIR_PATH
          env | grep REPORTS_DIR_PATH
          env | grep DICTIONARIES_DIR_PATH

      - name: Create directories
        run: |
          mkdir -p ${GLOBAL_PATH}${DATA_DIR_PATH}
          mkdir -p ${GLOBAL_PATH}${CARDS_DIR_PATH}
          mkdir -p ${GLOBAL_PATH}${LOGS_DIR_PATH}
          mkdir -p ${GLOBAL_PATH}${DATASETS_DIR_PATH}
          mkdir -p ${GLOBAL_PATH}${REPORTS_DIR_PATH}
          mkdir -p ${GLOBAL_PATH}${DICTIONARIES_DIR_PATH}

  download_data:
    runs-on: self-hosted
    needs: setup_directories
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Ustawienie Pythona
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Load environment variables
        run: |
          grep -v '^#' .env | while IFS= read -r line; do
            echo "$line" >> $GITHUB_ENV
          done

      - name: Debug environment variables
        run: |
          echo "Debugging environment variables in download_data step:"
          env

      - name: Install Poetry
        uses: snok/install-poetry@v1

      - name: Debug Poetry and Python
        run: |
          poetry --version
          python --version

      - name: Instalacja zależności
        run: poetry install

      - name: utwórz symlinks
        run: |
          ln -sfn ${GLOBAL_PATH}${DATA_DIR_PATH} ${DATA_DIR_PATH}
          ln -sfn ${GLOBAL_PATH}${CARDS_DIR_PATH} ${CARDS_DIR_PATH}
          ln -sfn ${GLOBAL_PATH}${LOGS_DIR_PATH} ${LOGS_DIR_PATH}
          ln -sfn ${GLOBAL_PATH}${DATASETS_DIR_PATH} ${DATASETS_DIR_PATH}
          ln -sfn ${GLOBAL_PATH}${REPORTS_DIR_PATH} ${REPORTS_DIR_PATH}
          ln -sfn ${GLOBAL_PATH}${DICTIONARIES_DIR_PATH} ${DICTIONARIES_DIR_PATH}

      - name: Uruchomienie download_bulk_data.py
        run: poetry run python ${DOWNLOAD_BULK_DATA_SCRIPT_PATH}

      - name: Uruchomienie download_types.py
        run: poetry run python ${DOWNLOAD_TYPES_SCRIPT_PATH}

  download_images:
    runs-on: self-hosted
    needs: download_data
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Ustawienie Pythona
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Load environment variables
        run: |
          grep -v '^#' .env | while IFS= read -r line; do
            echo "$line" >> $GITHUB_ENV
          done

      - name: Debug environment variables
        run: |
          echo "Debugging environment variables in download_data step:"
          env

      - name: Install Poetry
        uses: snok/install-poetry@v1

      - name: Instalacja zależności
        run: poetry install

      - name: utwórz symlinks
        run: |
          ln -sfn ${GLOBAL_PATH}${DATA_DIR_PATH} ${DATA_DIR_PATH}
          ln -sfn ${GLOBAL_PATH}${CARDS_DIR_PATH} ${CARDS_DIR_PATH}
          ln -sfn ${GLOBAL_PATH}${LOGS_DIR_PATH} ${LOGS_DIR_PATH}
          ln -sfn ${GLOBAL_PATH}${DATASETS_DIR_PATH} ${DATASETS_DIR_PATH}
          ln -sfn ${GLOBAL_PATH}${REPORTS_DIR_PATH} ${REPORTS_DIR_PATH}
          ln -sfn ${GLOBAL_PATH}${DICTIONARIES_DIR_PATH} ${DICTIONARIES_DIR_PATH}

      - name: Uruchomienie download_card_images.py
        run: poetry run python ${DOWNLOAD_IMAGES_SCRIPT_PATH}

  create_metadata:
    runs-on: self-hosted
    needs: download_images
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Ustawienie Pythona
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Load environment variables
        run: |
          grep -v '^#' .env | while IFS= read -r line; do
            echo "$line" >> $GITHUB_ENV
          done

      - name: Debug environment variables
        run: |
          echo "Debugging environment variables in create_metadata step:"
          env

      - name: Install Poetry
        uses: snok/install-poetry@v1

      - name: Instalacja zależności
        run: poetry install

      - name: utwórz symlinks
        run: |
          ln -sfn ${GLOBAL_PATH}${DATA_DIR_PATH} ${DATA_DIR_PATH}
          ln -sfn ${GLOBAL_PATH}${CARDS_DIR_PATH} ${CARDS_DIR_PATH}
          ln -sfn ${GLOBAL_PATH}${LOGS_DIR_PATH} ${LOGS_DIR_PATH}
          ln -sfn ${GLOBAL_PATH}${DATASETS_DIR_PATH} ${DATASETS_DIR_PATH}
          ln -sfn ${GLOBAL_PATH}${REPORTS_DIR_PATH} ${REPORTS_DIR_PATH}
          ln -sfn ${GLOBAL_PATH}${DICTIONARIES_DIR_PATH} ${DICTIONARIES_DIR_PATH}

      - name: Uruchomienie make_metadata_csv.py
        run: poetry run python ${CREATE_DATASET_SCRIPT_PATH}

  data_analysis:
    runs-on: self-hosted
    needs: create_metadata
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Ustawienie Pythona
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Load environment variables
        run: |
          grep -v '^#' .env | while IFS= read -r line; do
            echo "$line" >> $GITHUB_ENV
          done

      - name: Debug environment variables
        run: |
          echo "Debugging environment variables in data_analysis step:"
          env

      - name: Install Poetry
        uses: snok/install-poetry@v1

      - name: Instalacja zależności
        run: poetry install

      - name: utwórz symlinks
        run: |
          ln -sfn ${GLOBAL_PATH}${DATA_DIR_PATH} ${DATA_DIR_PATH}
          ln -sfn ${GLOBAL_PATH}${CARDS_DIR_PATH} ${CARDS_DIR_PATH}
          ln -sfn ${GLOBAL_PATH}${LOGS_DIR_PATH} ${LOGS_DIR_PATH}
          ln -sfn ${GLOBAL_PATH}${DATASETS_DIR_PATH} ${DATASETS_DIR_PATH}
          ln -sfn ${GLOBAL_PATH}${REPORTS_DIR_PATH} ${REPORTS_DIR_PATH}
          ln -sfn ${GLOBAL_PATH}${DICTIONARIES_DIR_PATH} ${DICTIONARIES_DIR_PATH}

      - name: Uruchomienie data_analysis.py
        run: poetry run python ${DATA_ANALYSIS_SCRIPT_PATH}
