name: MTG Card Prediction Workflow

on:
    push:
        branches:
          - main  
    workflow_dispatch:
    schedule:
    - cron: '0 0 * * *'  # Uruchamia się codziennie o północy

env:
  GLOBAL_PATH: "/home/kuba/mtg_project/"

jobs:
  setup_directories:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Load environment variables
        run: |
          grep -v '^#' .env | while read -r line; do
            echo "$line" >> $GITHUB_ENV
          done
      

      - name: Create directories and symlinks
        run: |
          mkdir -p ${{GLOBAL_PATH}}${{DATA_DIR_PATH}}
          mkdir -p ${{GLOBAL_PATH}}${{CARDS_DIR_PATH}}
          mkdir -p ${{GLOBAL_PATH}}${{LOGS_DIR_PATH}}
          mkdir -p ${{GLOBAL_PATH}}${{DATASETS_DIR_PATH}}
          mkdir -p ${{GLOBAL_PATH}}${{REPORTS_DIR_PATH}}
          mkdir -p ${{GLOBAL_PATH}}${{DICTIONARIES_DIR_PATH}}

          ln -sfn ${{GLOBAL_PATH}}${{DATA_DIR_PATH}} ${{DATA_DIR_PATH}}
          ln -sfn ${{GLOBAL_PATH}}${{CARDS_DIR_PATH}} ${{CARDS_DIR_PATH}}
          ln -sfn ${{GLOBAL_PATH}}${{LOGS_DIR_PATH}} ${{LOGS_DIR_PATH}}
          ln -sfn ${{GLOBAL_PATH}}${{REPORTS_DIR_PATH}} ${{REPORTS_DIR_PATH}}
          ln -sfn ${{GLOBAL_PATH}}${{DICTIONARIES_DIR_PATH}} ${{DICTIONARIES_DIR_PATH}}

  download_data:
    runs-on: self-hosted
    needs: setup_directories
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Ustawienie Pythona
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Poetry
        uses: snok/install-poetry@v1

      - name: Instalacja zależności
        run: poetry install 

      - name: Uruchomienie download_bulk_data.py
        run: poetry run python ${{DOWNLOAD_BULK_DATA_SCRIPT_PATH}}

      - name: Uruchomienie download_types.py
        run: poetry run python ${{DOWNLOAD_TYPES_SCRIPT_PATH}}

  download_images:
    runs-on: self-hosted
    needs: download_data
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Ustawienie Pythona
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Poetry
        uses: snok/install-poetry@v1

      - name: Instalacja zależności
        run: poetry install

      - name: Uruchomienie download_card_images.py
        run: poetry run python ${{DOWNLOAD_IMAGES_SCRIPT_PATH}}

  create_metadata:
    runs-on: self-hosted
    needs: download_images
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Ustawienie Pythona
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Poetry
        uses: snok/install-poetry@v1

      - name: Instalacja zależności
        run: poetry install

      - name: Uruchomienie make_metadata_csv.py
        run: poetry run python ${{CREATE_DATASET_SCRIPT_PATH}}

  data_analysis:
    runs-on: self-hosted
    needs: create_metadata
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Ustawienie Pythona
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Poetry
        uses: snok/install-poetry@v1

      - name: Instalacja zależności
        run: poetry install

      - name: Uruchomienie data_analysis.py
        run: poetry run python ${{DATA_ANALYSIS_SCRIPT_PATH}}
